cloudinary:
    api-key: 175631491224487
    api-secret: TmeGg3OGrfTjPGmY4Wj9cBnNYy8
    cloud-name: dzjoxccho
server:
    port: 8282
    error:
        include-message: always
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: sql12623547
        password: 2KxstzWfZi
        url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12623547?useUnicode=yes&characterEncoding=UTF-8
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                globally_quoted_identifiers: true
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    mail:
        host: smtp.gmail.com
        port: 587
        username: phancongtu25032002@gmail.com
        password: lvbmtkporezgjvyp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
mail:
    smtp:
        debug: true
jwt:
    secret: 1FE05E1FA7968F51E4A20A127CC2A16881CB909CD1A75C57C1A96C151C2B42AB
